import mongoose from 'mongoose';

const reservationSchema = new mongoose.Schema({
  numeroReserva: String,
  fechaCreacion: String,
  usuarioCreacion: String,
  sucursalCreacion: String,
  identificacionCliente: String,
  clienteNombre: String,
  estadoReserva: String,
  numeroDocumentoEmision: String,
  tipoDocumento: String,
  moneda: String,
  totalReserva: Number,
  totalDescuentos: Number,
  totalRecargos: Number,
  totalPagado: Number,
  fechaUltimoPago: String,
  numeroViaje: String,
  ruta: String,
  fechaZarpe: String,
  nave: String,
  equipoId: String,
  tipoEquipo: String,
  subTipoEquipo: String,
  patente: String,
  equipoAncho: String,
  equipoMli: String,
  equipoPeso: Number,
  equipoTara: Number,
  equipoPesoNeto: Number,
  tipoCarga: String,
  idDetalleCarga: String,
  condicionCarga: String,
  usuarioFacturacion: String,
  fechaFacturacion: String,
  tipoCliente: String,
  observaciones: String,
  unidadMedida: String,
  totalRackEquipo: Number,
  totalDescuentosEquipo: Number,
  totalRecargosEquipo: Number,
  observacionesComercial: String,
});

export default mongoose.model('Reservation', reservationSchema);
